### ISSUE TITLE
Reselecting the image does not update it

### ISSUE THREAD

**Issue by KrashV** [Silverfeelin/Starbound-NgOutfitGenerator#12]
If you try to select the same image as before, it does not update the preview and the generated pants.

**Steps to reproduce:**

1. Select "test.png" image for pants
2. Edit "test.png" in any redactor (Aseprite, Paint.net etc)
3. Select "test.png" once again
4. Generate the file

**Generated output:**
Pants for test.png before updating the source

**Expected output:**
Pants for test.png after updating the source

**Comment by Silverfeelin** [comment]
Sorry for the delay. That's a browser gimmick, where it doesn't detect the same file selection as a change. But since the selected file is already loaded, the new data will never be available.
There are some possible workarounds, I'll see if I can find a quick fix while working on #11
